gui:
  theme:
    selectedLineBgColor:
      - underline # set to `default` to have no background colour
    selectedRangeBgColor:
      - underline
  commitLength:
    show: true
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never