gui:
  theme:
    selectedLineBgColor:
      - underline # set to `default` to have no background colour
    selectedRangeBgColor:
      - underline
  commitLength:
    show: true
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true