require("jungai/plugins-setup")
require("jungai/core/options")
require("jungai/core/colorscheme")
require("jungai/core/keymaps")
require("jungai/plugins/comment")
require("jungai/plugins/tree")
require("jungai/plugins/telescope")
