require("jungai/plugins-setup")
require("jungai/core/options")
require("jungai/core/colorscheme")
require("jungai/core/keymaps")
require("jungai/plugins/comment")
require("jungai/plugins/tree")
require("jungai/plugins/telescope")
require("jungai/plugins/nvim-cmp")
require("jungai/plugins/mason")
require("jungai/plugins/lspconfig")
require("jungai/plugins/lspsaga")
require("jungai/plugins/null-ls")
require("jungai/plugins/autopairs")
require("jungai/plugins/treesitter")
require("jungai/plugins/todo-comment")
require("jungai/plugins/lualine")
-- require("jungai/plugins/flutter")