gui:
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  authorColors:
    '*': '#b4befe'
  showFileIcons: true
  nerdFontsVersion: "3"
  commitLength:
    show: true
git:
  log:
    showGraph: always
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
  - key: "B"
    command: "better-commits"
    description: "commit with better-commits"
    context: "files"
    loadingText: "running better-commits"
    subprocess: true